Version to 0.4.0 Requires Python 3.6 or above
Retire pyblake2.

Fix a build issue with buildozer related to pyblake2:
pyblake2module.c:699:27: error: expression is not assignable
Py_TYPE(&blake2bType) = &PyType_Type;
~~~~~~~~~~~~~~~~~~~~~ ^
pyblake2module.c:703:27: error: expression is not assignable
Py_TYPE(&blake2sType) = &PyType_Type;
~~~~~~~~~~~~~~~~~~~~~ ^
2 errors generated.
error: command '/home/ubuntu/.buildozer/android/platform/android-ndk-r25b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang' failed with exit code 1